name: NASA Project CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build client
        run: npm run build --prefix client
